### ISSUE TITLE
Types of acceptable outcome variables?

### ISSUE THREAD

**Issue by BrianMiner** [generalized-random-forests/grf#301]
Referencing #120 it appears from my reading that the use of this package with binary outcomes is considered acceptable and that the inference is valid. Is this correct? Should one consider any methods available in the package better that others under a binary outcome? Further, are there any distributional limitations on the outcome variable? Counts? Zero inflation?

**Comment by swager** [comment]
@BrianMiner yes that's correct -- GRF will work just fine with binary outcomes (including the confidence intervals). In the regression case, the forest will estimate the conditional probability `E[Y|X=x]`, and the CIs will cover this quantity asymptotically. We don't currently have any special-case tweaks for binary outcomes.

**Comment by BrianMiner** [comment]
Ok, the binary case work fine, which is great! Are you saying what is estimated is not the treatmenT effect though? 

I am curious also if when using a numeric outcome, is there assumptions of normality ( which would preclude use of a zero inflated gamma outcome for example)?

**Comment by BrianMiner** [comment]
Ok I understand what you mean about the regression case, I was not familiar that there was a non causual estimator (treatment minus control) in the package ( I.e. similar to classical rf), until I read a bit deeper.

I am curious if there are assumptions for continuous variables or if these methods (specifically causal forest) are applicable to counts, zero inflated variables etc.

**Comment by swager** [comment]
No worries! You can use this with continuous variables, count variables, etc -- all the results only rely on existence of second moments. Section 3 of https://arxiv.org/pdf/1610.01271.pdf spells out the (somewhat abstract) conditions we use for formal results.
